"""
update_cookies.py - 自动获取YouTube cookies并保存为Netscape格式

使用Playwright自动化浏览器，首次手动登录后可自动刷新cookies。

用法:
  首次设置:  python update_cookies.py --setup
  日常更新:  python update_cookies.py
  显示窗口:  python update_cookies.py --no-headless
  检查状态:  python update_cookies.py --check
"""

import os
import sys
import time
import json
import argparse
from pathlib import Path
from datetime import datetime

# ============ 配置 ============
SCRIPT_DIR = Path(__file__).parent
PROFILE_DIR = SCRIPT_DIR / ".browser_profile"        # Playwright浏览器配置目录
COOKIES_FILE = SCRIPT_DIR / "youtube_cookies.txt"    # 输出的cookies文件
YOUTUBE_URL = "https://www.youtube.com"

def _load_proxy():
    """从 yt_config.json 读取代理配置"""
    config_path = SCRIPT_DIR / "yt_config.json"
    if config_path.exists():
        try:
            cfg = json.loads(config_path.read_text(encoding="utf-8"))
            proxy_cfg = cfg.get("代理", {})
            if proxy_cfg.get("启用", False):
                proto = proxy_cfg.get("协议", "socks5")
                host = proxy_cfg.get("地址", "")
                port = proxy_cfg.get("端口", 1080)
                if host:
                    server = f"{proto}://{host}:{port}"
                    print(f"使用代理: {server}")
                    return {"server": server}
        except Exception as e:
            print(f"读取代理配置失败: {e}")
    print("未启用代理（直连）")
    return None

PLAYWRIGHT_PROXY = _load_proxy()
# ==============================


def cookies_to_netscape(cookies):
    """将Playwright cookies列表转换为Netscape cookies.txt格式"""
    lines = [
        "# Netscape HTTP Cookie File",
        f"# Generated by update_cookies.py at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        # Netscape格式: domain  flag  path  secure  expiration  name  value
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = int(c.get("expires", -1))
        if expires == -1:
            expires = 0  # 会话cookie
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def run_setup():
    """首次设置：打开可见浏览器，让用户手动登录Google账户"""
    from playwright.sync_api import sync_playwright

    PROFILE_DIR.mkdir(exist_ok=True)

    print("=" * 50)
    print("首次设置模式")
    print("=" * 50)
    print("即将打开浏览器，请在浏览器中：")
    print("  1. 访问 YouTube")
    print("  2. 登录你的 Google 账户")
    print("  3. 确认登录成功后，回到终端按回车")
    print("=" * 50)

    with sync_playwright() as p:
        kwargs = dict(
            user_data_dir=str(PROFILE_DIR),
            headless=False,
            viewport={"width": 1280, "height": 720},
            args=["--disable-blink-features=AutomationControlled"],
        )
        if PLAYWRIGHT_PROXY:
            kwargs["proxy"] = PLAYWRIGHT_PROXY
        browser = p.chromium.launch_persistent_context(**kwargs)
        page = browser.pages[0] if browser.pages else browser.new_page()
        page.goto(YOUTUBE_URL, wait_until="domcontentloaded")

        print("\n等待登录... 登录完成后按回车继续")
        input()

        # 等待页面稳定
        time.sleep(2)

        # 获取cookies
        cookies = browser.cookies()
        youtube_cookies = [c for c in cookies if "youtube.com" in c.get("domain", "")]

        if not youtube_cookies:
            print("警告：未获取到youtube.com的cookies，请确认已登录")
            input("按回车退出...")
            browser.close()
            return

        # 保存
        netscape_text = cookies_to_netscape(youtube_cookies)
        COOKIES_FILE.write_text(netscape_text, encoding="utf-8")
        print(f"\n已保存 {len(youtube_cookies)} 个cookie到 {COOKIES_FILE}")

        browser.close()

    print("\n设置完成！以后只需运行: python update_cookies.py")


def run_update(headless=True):
    """自动更新cookies：访问YouTube刷新token，导出cookies"""
    from playwright.sync_api import sync_playwright

    if not PROFILE_DIR.exists():
        print("错误：尚未设置浏览器配置。")
        print("请先运行: python update_cookies.py --setup")
        sys.exit(1)

    with sync_playwright() as p:
        kwargs = dict(
            user_data_dir=str(PROFILE_DIR),
            headless=headless,
            viewport={"width": 1280, "height": 720},
            args=["--disable-blink-features=AutomationControlled"],
        )
        if PLAYWRIGHT_PROXY:
            kwargs["proxy"] = PLAYWRIGHT_PROXY
        browser = p.chromium.launch_persistent_context(**kwargs)
        page = browser.pages[0] if browser.pages else browser.new_page()

        print("正在访问YouTube刷新cookies...")
        try:
            page.goto(YOUTUBE_URL, wait_until="networkidle", timeout=30000)
        except Exception:
            # networkidle超时也没关系，页面可能已经加载
            page.wait_for_load_state("domcontentloaded", timeout=15000)

        # 等待滚动token刷新
        print("等待cookies刷新...")
        time.sleep(5)

        # 获取cookies
        cookies = browser.cookies()
        youtube_cookies = [c for c in cookies if "youtube.com" in c.get("domain", "")]

        if not youtube_cookies:
            print("错误：未获取到youtube.com的cookies，登录可能已失效")
            print("请重新运行: python update_cookies.py --setup")
            browser.close()
            sys.exit(1)

        # 保存
        netscape_text = cookies_to_netscape(youtube_cookies)
        COOKIES_FILE.write_text(netscape_text, encoding="utf-8")

        # 统计关键cookie
        key_cookies = ["SID", "__Secure-1PSID", "__Secure-3PSID",
                       "SAPISID", "__Secure-1PAPISID", "LOGIN_INFO"]
        found_keys = [c["name"] for c in youtube_cookies if c["name"] in key_cookies]
        missing_keys = [k for k in key_cookies if k not in found_keys]

        print(f"\n已保存 {len(youtube_cookies)} 个cookie到 {COOKIES_FILE}")
        print(f"关键cookie: {len(found_keys)}/{len(key_cookies)} 已获取")
        if missing_keys:
            print(f"缺失: {', '.join(missing_keys)}")
            print("建议重新运行 --setup 登录")
        else:
            print("关键cookie齐全，可正常使用")

        # 显示最近的过期时间
        now = time.time()
        future_cookies = [c for c in youtube_cookies if c.get("expires", 0) > now]
        if future_cookies:
            earliest = min(c["expires"] for c in future_cookies)
            print(f"最近过期时间: {datetime.fromtimestamp(earliest).strftime('%Y-%m-%d %H:%M')}")

        browser.close()


def run_check():
    """检查当前cookies文件的状态"""
    if not COOKIES_FILE.exists():
        print("cookies文件不存在")
        return

    lines = COOKIES_FILE.read_text(encoding="utf-8").strip().split("\n")
    cookie_lines = [l for l in lines if l and not l.startswith("#")]

    now = time.time()
    active = 0
    expired = 0
    session = 0
    earliest_expire = float("inf")

    key_names = ["SID", "__Secure-1PSID", "__Secure-3PSID",
                 "SAPISID", "__Secure-1PAPISID", "LOGIN_INFO",
                 "__Secure-1PSIDTS", "__Secure-3PSIDTS"]
    key_status = {}

    for line in cookie_lines:
        parts = line.split("\t")
        if len(parts) < 7:
            continue
        name = parts[5]
        expires = int(parts[4])

        if expires == 0:
            session += 1
        elif expires > now:
            active += 1
            if expires < earliest_expire:
                earliest_expire = expires
        else:
            expired += 1

        if name in key_names:
            if expires == 0:
                key_status[name] = "会话级"
            elif expires > now:
                days_left = (expires - now) / 86400
                key_status[name] = f"有效 ({days_left:.0f}天后过期)"
            else:
                key_status[name] = "已过期"

    print("=" * 50)
    print("Cookies 文件状态")
    print("=" * 50)
    print(f"文件: {COOKIES_FILE}")
    print(f"修改时间: {datetime.fromtimestamp(COOKIES_FILE.stat().st_mtime).strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"总cookie数: {len(cookie_lines)}")
    print(f"  有效: {active}")
    print(f"  会话级: {session}")
    print(f"  已过期: {expired}")

    if earliest_expire != float("inf"):
        days = (earliest_expire - now) / 86400
        print(f"最近过期: {datetime.fromtimestamp(earliest_expire).strftime('%Y-%m-%d %H:%M')} ({days:.0f}天后)")

    print(f"\n关键cookie状态:")
    for name in key_names:
        status = key_status.get(name, "不存在")
        print(f"  {name:30s} {status}")

    # 建议
    has_expired_key = any("过期" in v for v in key_status.values())
    has_missing_key = any(name not in key_status for name in key_names)
    if has_expired_key or has_missing_key:
        print("\n建议: 部分关键cookie缺失或过期，请运行: python update_cookies.py")
    else:
        print("\n状态良好")


def main():
    parser = argparse.ArgumentParser(description="自动获取YouTube cookies")
    parser.add_argument("--setup", action="store_true",
                        help="首次设置，打开浏览器手动登录")
    parser.add_argument("--no-headless", action="store_true",
                        help="更新时显示浏览器窗口（调试用）")
    parser.add_argument("--check", action="store_true",
                        help="检查当前cookies文件状态")
    args = parser.parse_args()

    if args.check:
        run_check()
    elif args.setup:
        run_setup()
    else:
        run_update(headless=not args.no_headless)


if __name__ == "__main__":
    main()
